name: 'Copy Release'
description: 'Copy a release to another repository'
author: 'DanMass'
inputs:
  tag_name:
    description: 'Name of the tag associated with the Release to copy. If a tag is not provided, copy the latest Release.'
    required: true
  repo:
    description: 'Repository to which to copy the Release'
    required: false
outputs:
  id:
    description: 'The ID of the created Release'
  html_url:
    description: 'The URL users can navigate to in order to view the release'
  upload_url:
    description: 'The URL for uploading assets to the release'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'purple'
